### ISSUE TITLE
[feature] tables column

### ISSUE THREAD

**Issue by Athospd** [alastairrushworth/htmldf#8]
would be useful to bring a list with all tables from the HTML!

this package is an awesome idea, congrats.

**Comment by alastairrushworth** [comment]
Thanks @Athospd for the suggestion! I'll add this to the backlog, I think this would be a very useful addition.

**Comment by alastairrushworth** [comment]
Hey @Athospd 

I've now added a tables list column to the output of `htmldf`.  I need to test it a bit harder before pushing it up to CRAN, but in the meantime please give it a whirl and let me know if you find any problems!

**Comment by Athospd** [comment]
I'll surely test it out. Awesome!
